# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m
  go: "1.24.6"

# In v2, formatters and linters are separate
formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec
    - prealloc
    - gocritic
    - revive
